### ISSUE TITLE
Conflict with Datacenter/BusinessRules (Device Type of "Temperature" not "temperature")

### ISSUE THREAD

**Issue by MichaelFitzurka** [PatrickSteiner/IoT_Demo_Sensors#6]
Cross repository concern with IoT_Demo_BusinessRules, which looks for a Device Type of "Temperature" and not lower case "temperature" as established on DHTServerMQTT.ino
, line 122.
Could be addressed here, or in BusinessRules.

**Comment by PatrickSteiner** [comment]
Thanks for pointing this out!

I changed the topic names here instead of in BusinessRules.
